"use client";

import { useMemo, useState } from "react";

import { useConnection, useWallet } from "@solana/wallet-adapter-react";
import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import { VersionedTransaction } from "@solana/web3.js";
import Link from "next/link";
import { useParams } from "next/navigation";

import { decodeClaimBlob, type ClaimBlobV1 } from "@/lib/cove/claim-link";

type ClaimMetadata = {
  amount: string;
  mint: string;
  recipient: string;
  recentBlockhash: string;
  lastValidBlockHeight: number | null;
};

type ClaimPrepareResponse =
  | {
      mode: "user_sign";
      unsignedTransactionBase64: string;
      metadata: ClaimMetadata;
    }
  | {
      mode: "relay_submitted";
      signature: string;
      metadata: ClaimMetadata;
    };

type SubmissionMode = "user_sign" | "relay_submitted";

type Status =
  | { kind: "idle" }
  | { kind: "preparing" }
  | { kind: "signing" }
  | { kind: "submitting" }
  | { kind: "confirming"; signature: string }
  | { kind: "success"; signature: string; mode: SubmissionMode }
  | { kind: "error"; message: string };

function base64ToBytes(b64: string): Uint8Array {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function lamportsToSol(lamportsStr: string): string {
  // Display-only conversion. We deliberately avoid Number() rounding for
  // values near JS safe-integer; format as a decimal string instead.
  const lamports = BigInt(lamportsStr);
  const whole = lamports / 1_000_000_000n;
  const frac = lamports % 1_000_000_000n;
  const fracStr = frac.toString().padStart(9, "0").replace(/0+$/, "");
  return fracStr.length > 0 ? `${whole}.${fracStr}` : whole.toString();
}

export default function ClaimPage() {
  const params = useParams<{ blob: string }>();
  const { connection } = useConnection();
  const { publicKey, signTransaction, connected } = useWallet();
  const [status, setStatus] = useState<Status>({ kind: "idle" });

  // Decode the URL blob once. Memoized so we don't reparse on every render.
  const decoded = useMemo<
    | { ok: true; blob: ClaimBlobV1 }
    | { ok: false; reason: string }
  >(() => {
    const raw = params?.blob;
    if (!raw || typeof raw !== "string") {
      return { ok: false, reason: "no claim payload in URL" };
    }
    try {
      const blob = decodeClaimBlob(raw);
      if (!blob.r) {
        return {
          ok: false,
          reason:
            "this claim link is missing the blinding factor (r) and cannot be redeemed. it was likely generated by an older version of Cove",
        };
      }
      return { ok: true, blob };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { ok: false, reason: `failed to decode claim link: ${msg}` };
    }
  }, [params?.blob]);

  const canClaim =
    decoded.ok &&
    connected &&
    publicKey &&
    signTransaction &&
    status.kind !== "preparing" &&
    status.kind !== "signing" &&
    status.kind !== "submitting" &&
    status.kind !== "confirming";

  async function handleClaim() {
    if (!decoded.ok || !publicKey || !signTransaction) return;
    const blob = decoded.blob;

    setStatus({ kind: "preparing" });
    try {
      // 1. Ask the server to build the unsigned withdraw tx (proof + tx).
      const res = await fetch("/api/claim/prepare", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          utxoOwnerPrivateKeyHex: blob.sk,
          blindingHex: blob.r,
          amount: blob.amt,
          mint: blob.mint,
          commitmentIndex: blob.idx,
          expectedCommitment: blob.cm,
          expectedSiblingCommitment: blob.sib,
          recipientWalletPublicKey: publicKey.toBase58(),
        }),
      });
      if (!res.ok) {
        const errBody = (await res.json().catch(() => ({}))) as {
          error?: string;
        };
        throw new Error(errBody.error ?? `prepare failed: ${res.status}`);
      }
      const prepared = (await res.json()) as ClaimPrepareResponse;

      // 2. Two possible paths from the route:
      //    - relay_submitted: Cove relay already submitted the tx with its own
      //      wallet. We just confirm on chain (use the route's blockhash).
      //    - user_sign: SDK fell back to direct submission. Client signs and
      //      submits. The route's blockhash is stale (proof gen + think time
      //      can exceed Solana's ~90s window), so we refresh before signing
      //      and confirm against the fresh strategy.
      let signature: string;
      let confirmBlockhash = prepared.metadata.recentBlockhash;
      let confirmLastValidBlockHeight =
        prepared.metadata.lastValidBlockHeight ?? 0;

      if (prepared.mode === "relay_submitted") {
        signature = prepared.signature;
        // Skip signing/submitting entirely. Relay already used its own
        // blockhash; we keep the route-supplied strategy as our polling bound.
      } else {
        const tx = VersionedTransaction.deserialize(
          base64ToBytes(prepared.unsignedTransactionBase64),
        );
        const refreshed = await connection.getLatestBlockhash("confirmed");
        tx.message.recentBlockhash = refreshed.blockhash;
        confirmBlockhash = refreshed.blockhash;
        confirmLastValidBlockHeight = refreshed.lastValidBlockHeight;

        setStatus({ kind: "signing" });
        const signed = await signTransaction(tx);

        setStatus({ kind: "submitting" });
        signature = await connection.sendRawTransaction(signed.serialize(), {
          skipPreflight: false,
        });
      }

      // 3. Confirm on chain.
      setStatus({ kind: "confirming", signature });
      const confirmation = await connection.confirmTransaction(
        {
          signature,
          blockhash: confirmBlockhash,
          lastValidBlockHeight: confirmLastValidBlockHeight,
        },
        "confirmed",
      );
      if (confirmation.value.err) {
        throw new Error(
          `confirmation error: ${JSON.stringify(confirmation.value.err)}`,
        );
      }

      console.log(
        `[cove/claim] withdraw signature (${prepared.mode}):`,
        signature,
      );
      setStatus({ kind: "success", signature, mode: prepared.mode });
    } catch (err) {
      console.error("[cove/claim] failed:", err);
      setStatus({
        kind: "error",
        message: err instanceof Error ? err.message : String(err),
      });
    }
  }

  return (
    <div className="min-h-screen flex flex-col">
      <header className="flex items-center justify-between px-6 py-4 border-b border-zinc-200 dark:border-zinc-800">
        <span className="text-xl font-semibold tracking-tight">Cove</span>
        <div className="flex items-center gap-4">
          <Link
            href="/dashboard"
            className="text-sm text-zinc-500 hover:underline"
          >
            Dashboard
          </Link>
          <WalletMultiButton />
        </div>
      </header>

      <main className="flex flex-1 items-center justify-center px-6 py-12">
        <div className="w-full max-w-md rounded-xl border border-zinc-200 dark:border-zinc-800 p-6 space-y-4 bg-white dark:bg-zinc-950">
          <h1 className="text-xl font-semibold">Claim a private payment</h1>

          {!decoded.ok ? (
            <div className="rounded-md border border-red-300 bg-red-50 dark:bg-red-950/30 dark:border-red-900 p-3 text-sm text-red-700 dark:text-red-300">
              {decoded.reason}
            </div>
          ) : (
            <>
              <div className="rounded-md border border-zinc-200 dark:border-zinc-800 p-3">
                <p className="text-xs text-zinc-500">Amount</p>
                <p className="text-2xl font-semibold tabular-nums">
                  {lamportsToSol(decoded.blob.amt)} SOL
                </p>
              </div>

              {connected && publicKey && (
                <p className="text-xs text-zinc-500 break-all">
                  Will be sent to{" "}
                  <span className="font-mono">{publicKey.toBase58()}</span>
                </p>
              )}

              <button
                onClick={handleClaim}
                disabled={!canClaim}
                className="w-full rounded-md bg-zinc-900 dark:bg-zinc-100 text-white dark:text-zinc-900 py-2 font-medium disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Claim to my wallet
              </button>

              <ClaimStatusPanel status={status} connected={connected} />
            </>
          )}
        </div>
      </main>
    </div>
  );
}

function ClaimStatusPanel({
  status,
  connected,
}: {
  status: Status;
  connected: boolean;
}) {
  if (status.kind === "idle") {
    return (
      <p className="text-sm text-zinc-500">
        {connected ? "Ready." : "Connect a wallet to begin."}
      </p>
    );
  }
  if (status.kind === "preparing") {
    return (
      <p className="text-sm text-zinc-500">
        Preparing claim (proof generation, ~10–30s)...
      </p>
    );
  }
  if (status.kind === "signing") {
    return (
      <p className="text-sm text-zinc-500">Waiting for wallet signature...</p>
    );
  }
  if (status.kind === "submitting") {
    return <p className="text-sm text-zinc-500">Submitting transaction...</p>;
  }
  if (status.kind === "confirming") {
    return (
      <p className="text-sm text-zinc-500">
        Confirming on chain...{" "}
        <span className="font-mono">{status.signature.slice(0, 12)}…</span>
      </p>
    );
  }
  if (status.kind === "error") {
    return (
      <div className="rounded-md border border-red-300 bg-red-50 dark:bg-red-950/30 dark:border-red-900 p-3 text-sm text-red-700 dark:text-red-300">
        {status.message}
      </div>
    );
  }

  // success
  return (
    <div className="space-y-2">
      <div className="rounded-md border border-green-300 bg-green-50 dark:bg-green-950/30 dark:border-green-900 p-3 text-sm text-green-700 dark:text-green-300">
        Claim confirmed.
      </div>
      {status.mode === "relay_submitted" && (
        <p className="text-xs text-zinc-500">
          Claimed via Cove relay. No transaction fee was paid by your wallet.
        </p>
      )}
      <p className="text-xs text-zinc-500 break-all">
        Signature: <span className="font-mono">{status.signature}</span>
      </p>
      <a
        className="text-xs text-zinc-500 underline"
        href={`https://solscan.io/tx/${status.signature}`}
        target="_blank"
        rel="noreferrer"
      >
        View on Solscan
      </a>
    </div>
  );
}
