"use client";

import { motion } from "framer-motion";
import Link from "next/link";

import {
  CoveNavbar,
  CovePage,
  PageReveal,
  SectionEyebrow,
  fadeUp,
  primaryButtonClass,
} from "@/components/cove-ui";

const takeaways = [
  "Cove is designed to shield payment details on-chain, but ordinary web infrastructure can still observe basic connection metadata.",
  "We do not track, store, or sell the underlying financial details of private settlements generated through the interface.",
  "Users remain responsible for wallet security, claim-link handling, and understanding the limits of privacy across browsers, RPCs, and hosting providers.",
];

const sections = [
  {
    title: "1. On-Chain Privacy vs. Web Telemetry",
    body: [
      "Cove is built to improve privacy for payments executed on Solana, but blockchain privacy and web privacy are not the same thing. Our interface is meant to reduce public linkage between sender and recipient on-chain, not to eliminate every trace generated by internet infrastructure.",
      "When you load the site, standard web systems may process ordinary connection data such as IP address, device information, browser version, and request timing. That information is different from the private settlement data handled by the protocol layer.",
    ],
  },
  {
    title: "2. Information Handled by the Interface",
    body: [
      "The interface may temporarily process wallet public keys, token selections, transaction payloads, claim-link blobs, and local browser state needed to prepare or recover a transaction flow. Some of this information may be stored locally on your device so an in-progress deposit or claim can be resumed.",
      "Cove does not require account creation for ordinary use of the interface, and we do not operate a user database of balances, recipients, or private transaction histories tied to named profiles.",
    ],
  },
  {
    title: "3. Zero-Knowledge Proof Mechanics",
    body: [
      "Our privacy model relies on zero-knowledge proofs and shielded settlement flows provided through the Cloak SDK on Solana. While transaction amounts and addresses are shielded on-chain via ZK-proofs, standard web hosting infrastructure (Vercel) may log basic connection data like IP addresses.",
      "We do not track, store, or sell underlying financial data. Cove does not maintain a separate ledger of who paid whom, how much was privately settled, or which claim links were ultimately redeemed beyond the transient processing necessary to complete the requested action.",
    ],
  },
  {
    title: "4. Third-Party Infrastructure",
    body: [
      "Cove depends on third-party services to function, including wallet providers, Solana RPC infrastructure, hosting, relay services, and open-source libraries. Those providers may have their own privacy practices, logging, and retention policies.",
      "Where a third party is necessary for transaction submission, proof generation, delivery, or page hosting, your use of Cove may also expose limited operational metadata to that provider. Users should review those providers independently when evaluating overall risk.",
    ],
  },
  {
    title: "5. Data Retention & User Rights",
    body: [
      "Cove aims to minimize retention. Browser-side state may remain on your device until you clear it, and infrastructure logs maintained by service providers may persist according to their own schedules. We do not sell personal data and do not intentionally build behavioral profiles around private financial activity.",
      "If you have questions about data handling or need clarification on what the interface processes, you may contact Cove through official channels. Because Cove is non-custodial, many actions involving wallets, on-chain transactions, or claim links cannot be reversed or deleted once executed.",
    ],
  },
];

export default function PrivacyPage() {
  return (
    <CovePage
      navbar={<CoveNavbar cta={{ label: "Launch Cove", href: "/send" }} />}
      contentClassName="py-10 sm:py-14"
    >
      <PageReveal className="mx-auto w-full max-w-5xl">
        <motion.section variants={fadeUp} className="rounded-[32px] border border-zinc-800 bg-zinc-950 px-6 py-10 text-zinc-100 shadow-[0_20px_80px_rgba(0,0,0,0.45)] sm:px-8 md:px-12">
          <SectionEyebrow>Legal</SectionEyebrow>
          <h1 className="mt-6 max-w-3xl font-syne text-4xl font-bold tracking-tighter text-white sm:text-5xl">
            Privacy Policy
          </h1>
          <p className="mt-4 max-w-2xl font-inter text-base leading-7 text-zinc-400">
            This policy explains the privacy boundaries of Cove&apos;s interface, including
            what is shielded on-chain, what ordinary web systems may still observe, and
            how we think about data minimization.
          </p>

          <div className="mt-10 rounded-3xl border border-zinc-800 bg-zinc-900/80 p-6">
            <div className="flex items-center justify-between gap-4">
              <h2 className="font-syne text-2xl font-semibold tracking-tighter text-white">
                At a Glance
              </h2>
              <span className="rounded-full border border-zinc-700 px-3 py-1 text-[11px] font-inter uppercase tracking-[0.24em] text-[#DA4022]">
                Quick Summary
              </span>
            </div>
            <div className="mt-5 space-y-3">
              {takeaways.map((item) => (
                <div
                  key={item}
                  className="rounded-2xl border border-zinc-800 bg-black/30 px-4 py-4 font-inter text-sm leading-6 text-zinc-300"
                >
                  {item}
                </div>
              ))}
            </div>
          </div>

          <div className="mx-auto mt-12 max-w-prose space-y-10 font-inter text-[15px] leading-8 text-zinc-300">
            {sections.map((section) => (
              <section key={section.title} className="space-y-4">
                <h2 className="font-syne text-2xl font-semibold tracking-tighter text-white">
                  {section.title}
                </h2>
                {section.body.map((paragraph) => (
                  <p key={paragraph}>{paragraph}</p>
                ))}
              </section>
            ))}
          </div>

          <div className="mt-12 flex flex-col gap-4 border-t border-zinc-800 pt-8 text-sm text-zinc-400 sm:flex-row sm:items-center sm:justify-between">
            <p className="max-w-2xl font-inter">
              Privacy in web3 is layered. Cove improves on-chain privacy, but users should
              still evaluate wallets, browsers, hosting providers, and network routing as
              part of their threat model.
            </p>
            <Link href="/terms" className={`${primaryButtonClass} shrink-0`}>
              View Terms
            </Link>
          </div>
        </motion.section>
      </PageReveal>
    </CovePage>
  );
}
